import type { Client, Task, Project, Invoice, OutreachLead, CalendarEvent, Contact, MeetingNote, ActivityEntry, Goal, Service, Campaign } from './store'

// Stable IDs for cross-referencing
const CLIENT_IDS = {
  aurora: 'demo-client-001',
  pinnacle: 'demo-client-002',
  greenleaf: 'demo-client-003',
  velociti: 'demo-client-004',
}

export const demoClients: Client[] = [
  {
    id: CLIENT_IDS.aurora,
    name: 'Aurora Wellness Spa',
    service: 'Social Media Management',
    retainer: 'Monthly',
    mrr: 2500,
    status: 'active',
    platform: 'Instagram, Facebook',
    contact: 'Sarah Mitchell',
    email: 'sarah@aurorawellness.com',
    phone: '780-555-0142',
    website: 'https://aurorawellness.com',
    colors: '#7C3AED, #F9A8D4',
    logo_path: null,
    last_activity: '2026-04-04',
    notes: 'Launching new membership tier in May. Wants reels strategy.',
    tags: 'wellness,social,retainer',
    created_at: '2025-09-15T10:00:00Z',
    updated_at: '2026-04-04T14:30:00Z',
  },
  {
    id: CLIENT_IDS.pinnacle,
    name: 'Pinnacle Auto Group',
    service: 'Google Ads + SEO',
    retainer: 'Monthly',
    mrr: 4200,
    status: 'active',
    platform: 'Google Ads, SEO',
    contact: 'James Redford',
    email: 'james@pinnacleauto.ca',
    phone: '780-555-0287',
    website: 'https://pinnacleauto.ca',
    colors: '#1E40AF, #EF4444',
    logo_path: null,
    last_activity: '2026-04-05',
    notes: 'Spring sale campaign launching April 15. Budget increase approved.',
    tags: 'automotive,ppc,seo,retainer',
    created_at: '2025-06-01T08:00:00Z',
    updated_at: '2026-04-05T09:15:00Z',
  },
  {
    id: CLIENT_IDS.greenleaf,
    name: 'Greenleaf Landscaping',
    service: 'Website + Local SEO',
    retainer: null,
    mrr: 1800,
    status: 'active',
    platform: 'WordPress, Google Business',
    contact: 'Mike Chen',
    email: 'mike@greenleafyeg.ca',
    phone: '780-555-0391',
    website: 'https://greenleafyeg.ca',
    colors: '#16A34A, #A3E635',
    logo_path: null,
    last_activity: '2026-04-02',
    notes: 'Seasonal push starting — needs spring landing page.',
    tags: 'landscaping,seo,web',
    created_at: '2025-11-20T12:00:00Z',
    updated_at: '2026-04-02T16:45:00Z',
  },
  {
    id: CLIENT_IDS.velociti,
    name: 'Velociti Fitness',
    service: 'Full Digital Package',
    retainer: 'Monthly',
    mrr: 3500,
    status: 'active',
    platform: 'Meta Ads, Google Ads, TikTok',
    contact: 'Priya Sharma',
    email: 'priya@velocitifitness.com',
    phone: '780-555-0468',
    website: 'https://velocitifitness.com',
    colors: '#F97316, #0EA5E9',
    logo_path: null,
    last_activity: '2026-04-06',
    notes: 'Grand opening of second location May 1. Big ad push planned.',
    tags: 'fitness,ads,social,retainer',
    created_at: '2025-08-10T09:00:00Z',
    updated_at: '2026-04-06T11:20:00Z',
  },
]

export const demoTasks: Task[] = [
  {
    id: 'demo-task-001',
    text: 'Design spring sale ad creatives for Pinnacle Auto',
    description: '3 responsive display ads + 2 search ad variations',
    priority: 'high',
    done: 0,
    client_id: CLIENT_IDS.pinnacle,
    client_name: 'Pinnacle Auto Group',
    due_date: '2026-04-10',
    tags: 'ads,design',
    recurring: null,
    created_at: '2026-04-01T08:00:00Z',
    completed_at: null,
  },
  {
    id: 'demo-task-002',
    text: 'Publish April content calendar for Aurora Wellness',
    description: 'Finalize 12 posts for Instagram and Facebook',
    priority: 'medium',
    done: 1,
    client_id: CLIENT_IDS.aurora,
    client_name: 'Aurora Wellness Spa',
    due_date: '2026-04-03',
    tags: 'content,social',
    recurring: 'monthly',
    created_at: '2026-03-28T10:00:00Z',
    completed_at: '2026-04-02T15:30:00Z',
  },
  {
    id: 'demo-task-003',
    text: 'Build spring landing page for Greenleaf',
    description: 'Include service list, before/after gallery, quote form',
    priority: 'high',
    done: 0,
    client_id: CLIENT_IDS.greenleaf,
    client_name: 'Greenleaf Landscaping',
    due_date: '2026-04-12',
    tags: 'web,design',
    recurring: null,
    created_at: '2026-04-02T09:00:00Z',
    completed_at: null,
  },
  {
    id: 'demo-task-004',
    text: 'Set up TikTok pixel for Velociti Fitness',
    description: 'Install pixel on website and verify conversion events',
    priority: 'medium',
    done: 0,
    client_id: CLIENT_IDS.velociti,
    client_name: 'Velociti Fitness',
    due_date: '2026-04-08',
    tags: 'tracking,ads',
    recurring: null,
    created_at: '2026-04-03T14:00:00Z',
    completed_at: null,
  },
  {
    id: 'demo-task-005',
    text: 'Send monthly performance report to all retainer clients',
    description: null,
    priority: 'medium',
    done: 0,
    client_id: null,
    client_name: undefined,
    due_date: '2026-04-07',
    tags: 'reporting',
    recurring: 'monthly',
    created_at: '2026-04-01T07:00:00Z',
    completed_at: null,
  },
  {
    id: 'demo-task-006',
    text: 'Audit Google Ads account structure for Pinnacle',
    description: 'Check negative keywords, ad extensions, bid strategy',
    priority: 'low',
    done: 1,
    client_id: CLIENT_IDS.pinnacle,
    client_name: 'Pinnacle Auto Group',
    due_date: '2026-04-01',
    tags: 'ppc,audit',
    recurring: null,
    created_at: '2026-03-25T11:00:00Z',
    completed_at: '2026-03-31T16:00:00Z',
  },
]

export const demoProjects: Project[] = [
  {
    id: 'demo-proj-001',
    client_id: CLIENT_IDS.pinnacle,
    client_name: 'Pinnacle Auto Group',
    title: 'Spring Sale Campaign 2026',
    description: 'Full campaign — Google Ads, display, remarketing, landing page',
    priority: 'high',
    status: 'progress',
    due_date: '2026-04-15',
    hours: 24,
    links: 'https://ads.google.com',
    recurring: null,
    created_at: '2026-03-20T08:00:00Z',
    updated_at: '2026-04-05T10:00:00Z',
  },
  {
    id: 'demo-proj-002',
    client_id: CLIENT_IDS.velociti,
    client_name: 'Velociti Fitness',
    title: 'Grand Opening — Location #2',
    description: 'Multi-platform launch campaign for new gym location',
    priority: 'high',
    status: 'backlog',
    due_date: '2026-05-01',
    hours: 40,
    links: null,
    recurring: null,
    created_at: '2026-04-01T09:00:00Z',
    updated_at: '2026-04-06T11:00:00Z',
  },
  {
    id: 'demo-proj-003',
    client_id: CLIENT_IDS.greenleaf,
    client_name: 'Greenleaf Landscaping',
    title: 'Website Redesign + SEO',
    description: 'New WordPress theme, speed optimization, local SEO setup',
    priority: 'medium',
    status: 'progress',
    due_date: '2026-04-20',
    hours: 18,
    links: null,
    recurring: null,
    created_at: '2026-03-01T12:00:00Z',
    updated_at: '2026-04-02T16:00:00Z',
  },
]

export const demoInvoices: Invoice[] = [
  {
    id: 'demo-inv-001',
    num: 'GTH-042',
    client_id: CLIENT_IDS.pinnacle,
    client_name: 'Pinnacle Auto Group',
    amount: 4200,
    sent_date: '2026-04-01',
    due_date: '2026-04-15',
    status: 'sent',
    file_path: null,
    notes: 'April retainer',
    created_at: '2026-04-01T08:00:00Z',
    paid_at: null,
  },
  {
    id: 'demo-inv-002',
    num: 'GTH-041',
    client_id: CLIENT_IDS.aurora,
    client_name: 'Aurora Wellness Spa',
    amount: 2500,
    sent_date: '2026-04-01',
    due_date: '2026-04-15',
    status: 'sent',
    file_path: null,
    notes: 'April retainer — social media management',
    created_at: '2026-04-01T08:10:00Z',
    paid_at: null,
  },
  {
    id: 'demo-inv-003',
    num: 'GTH-040',
    client_id: CLIENT_IDS.velociti,
    client_name: 'Velociti Fitness',
    amount: 3500,
    sent_date: '2026-03-01',
    due_date: '2026-03-15',
    status: 'paid',
    file_path: null,
    notes: 'March retainer',
    created_at: '2026-03-01T08:00:00Z',
    paid_at: '2026-03-12T10:30:00Z',
  },
  {
    id: 'demo-inv-004',
    num: 'GTH-039',
    client_id: CLIENT_IDS.greenleaf,
    client_name: 'Greenleaf Landscaping',
    amount: 1800,
    sent_date: '2026-03-01',
    due_date: '2026-03-15',
    status: 'paid',
    file_path: null,
    notes: 'March — website + SEO',
    created_at: '2026-03-01T08:15:00Z',
    paid_at: '2026-03-14T09:00:00Z',
  },
  {
    id: 'demo-inv-005',
    num: 'GTH-038',
    client_id: CLIENT_IDS.pinnacle,
    client_name: 'Pinnacle Auto Group',
    amount: 4200,
    sent_date: '2026-03-01',
    due_date: '2026-03-15',
    status: 'paid',
    file_path: null,
    notes: 'March retainer',
    created_at: '2026-03-01T07:50:00Z',
    paid_at: '2026-03-10T14:00:00Z',
  },
]

export const demoContacts: Contact[] = [
  {
    id: 'demo-contact-001',
    client_id: CLIENT_IDS.aurora,
    client_name: 'Aurora Wellness Spa',
    name: 'Sarah Mitchell',
    role: 'Owner',
    email: 'sarah@aurorawellness.com',
    phone: '780-555-0142',
    is_primary: 1,
    notes: 'Prefers text over email. Responsive on weekdays.',
    last_contacted: '2026-04-04',
    created_at: '2025-09-15T10:00:00Z',
  },
  {
    id: 'demo-contact-002',
    client_id: CLIENT_IDS.pinnacle,
    client_name: 'Pinnacle Auto Group',
    name: 'James Redford',
    role: 'Marketing Director',
    email: 'james@pinnacleauto.ca',
    phone: '780-555-0287',
    is_primary: 1,
    notes: 'Weekly Monday check-in calls.',
    last_contacted: '2026-04-05',
    created_at: '2025-06-01T08:00:00Z',
  },
  {
    id: 'demo-contact-003',
    client_id: CLIENT_IDS.greenleaf,
    client_name: 'Greenleaf Landscaping',
    name: 'Mike Chen',
    role: 'Owner',
    email: 'mike@greenleafyeg.ca',
    phone: '780-555-0391',
    is_primary: 1,
    notes: 'Best reached after 4pm.',
    last_contacted: '2026-04-02',
    created_at: '2025-11-20T12:00:00Z',
  },
  {
    id: 'demo-contact-004',
    client_id: CLIENT_IDS.velociti,
    client_name: 'Velociti Fitness',
    name: 'Priya Sharma',
    role: 'Founder & CEO',
    email: 'priya@velocitifitness.com',
    phone: '780-555-0468',
    is_primary: 1,
    notes: 'Very hands-on. Likes seeing data before meetings.',
    last_contacted: '2026-04-06',
    created_at: '2025-08-10T09:00:00Z',
  },
  {
    id: 'demo-contact-005',
    client_id: CLIENT_IDS.pinnacle,
    client_name: 'Pinnacle Auto Group',
    name: 'Linda Torres',
    role: 'General Manager',
    email: 'linda@pinnacleauto.ca',
    phone: '780-555-0299',
    is_primary: 0,
    notes: 'Approves budgets. CC on major proposals.',
    last_contacted: '2026-03-20',
    created_at: '2025-07-15T10:00:00Z',
  },
]

export const demoLeads: OutreachLead[] = [
  {
    id: 'demo-lead-001',
    name: 'Summit Dental Clinic',
    industry: 'Healthcare',
    stage: 'Responded',
    last_contact: '2026-04-03',
    next_follow_up: '2026-04-09',
    deal_value: 2000,
    notes: 'Interested in Google Ads + local SEO. Proposal sent.',
    created_at: '2026-03-20T10:00:00Z',
    converted_client_id: null,
  },
  {
    id: 'demo-lead-002',
    name: 'Northside Brewing Co.',
    industry: 'Food & Beverage',
    stage: 'Contacted',
    last_contact: '2026-04-01',
    next_follow_up: '2026-04-08',
    deal_value: 1500,
    notes: 'Met at networking event. Needs social media help.',
    created_at: '2026-03-28T14:00:00Z',
    converted_client_id: null,
  },
  {
    id: 'demo-lead-003',
    name: 'Apex Real Estate',
    industry: 'Real Estate',
    stage: 'Meeting Set',
    last_contact: '2026-04-05',
    next_follow_up: '2026-04-12',
    deal_value: 3500,
    notes: 'Referral from James at Pinnacle. Discovery call booked.',
    created_at: '2026-04-04T09:00:00Z',
    converted_client_id: null,
  },
]

export const demoEvents: CalendarEvent[] = [
  {
    id: 'demo-event-001',
    date: '2026-04-07',
    start_time: '10:00',
    end_time: '10:30',
    title: 'Weekly check-in — Pinnacle Auto',
    type: 'call',
    client_id: CLIENT_IDS.pinnacle,
    client_name: 'Pinnacle Auto Group',
    recurring: 'weekly',
    created_at: '2026-01-06T08:00:00Z',
  },
  {
    id: 'demo-event-002',
    date: '2026-04-08',
    start_time: '14:00',
    end_time: '15:00',
    title: 'Grand opening strategy — Velociti',
    type: 'meeting',
    client_id: CLIENT_IDS.velociti,
    client_name: 'Velociti Fitness',
    recurring: null,
    created_at: '2026-04-03T09:00:00Z',
  },
  {
    id: 'demo-event-003',
    date: '2026-04-09',
    start_time: '09:00',
    end_time: '09:30',
    title: 'Follow-up call — Summit Dental',
    type: 'call',
    client_id: null,
    client_name: undefined,
    recurring: null,
    created_at: '2026-04-05T11:00:00Z',
  },
]

export const demoMeetings: MeetingNote[] = [
  {
    id: 'demo-meeting-001',
    client_id: CLIENT_IDS.pinnacle,
    client_name: 'Pinnacle Auto Group',
    contact_id: 'demo-contact-002',
    contact_name: 'James Redford',
    title: 'Spring Sale Campaign Kickoff',
    date: '2026-03-25',
    type: 'video',
    attendees: 'James Redford, Linda Torres',
    notes: 'Discussed campaign goals: 150+ leads, $50 target CPL. Budget $6k/mo for April-May. Approved display + search + remarketing.',
    action_items: 'Build campaign structure by April 1\nDesign ad creatives by April 10\nSet up conversion tracking',
    created_at: '2026-03-25T11:00:00Z',
  },
]

export const demoCampaigns: Campaign[] = [
  {
    id: 'demo-campaign-001',
    client_id: CLIENT_IDS.pinnacle,
    client_name: 'Pinnacle Auto Group',
    platform: 'Google Ads',
    name: 'Spring Sale — Search',
    status: 'active',
    spend: 1850,
    conversions: 42,
    updated_at: '2026-04-05T09:00:00Z',
  },
  {
    id: 'demo-campaign-002',
    client_id: CLIENT_IDS.velociti,
    client_name: 'Velociti Fitness',
    platform: 'Meta Ads',
    name: 'Membership Promo — April',
    status: 'active',
    spend: 920,
    conversions: 28,
    updated_at: '2026-04-05T10:00:00Z',
  },
]

export const demoGoals: Goal[] = [
  {
    id: 'demo-goal-001',
    title: 'Hit $15k MRR',
    description: 'Grow monthly recurring revenue to $15,000',
    metric_type: 'revenue',
    target_value: 15000,
    current_value: 12000,
    target_date: '2026-06-30',
    status: 'in-progress',
    created_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 'demo-goal-002',
    title: 'Close 2 new retainer clients this quarter',
    description: null,
    metric_type: 'count',
    target_value: 2,
    current_value: 0,
    target_date: '2026-06-30',
    status: 'in-progress',
    created_at: '2026-04-01T08:00:00Z',
  },
]

export const demoServices: Service[] = [
  {
    id: 'demo-svc-001',
    name: 'Social Media Management',
    category: 'Social',
    description: 'Content creation, scheduling, engagement, monthly reporting',
    pricing_model: 'monthly',
    default_price: 2500,
    typical_hours: 20,
    deliverables: '12 posts/mo, stories, engagement, monthly report',
    active: 1,
    created_at: '2025-01-01T08:00:00Z',
  },
  {
    id: 'demo-svc-002',
    name: 'Google Ads Management',
    category: 'PPC',
    description: 'Campaign setup, optimization, reporting',
    pricing_model: 'monthly',
    default_price: 1500,
    typical_hours: 10,
    deliverables: 'Campaign management, bi-weekly optimization, monthly report',
    active: 1,
    created_at: '2025-01-01T08:00:00Z',
  },
]

export const demoActivity: ActivityEntry[] = [
  {
    id: 'demo-act-001',
    type: 'update',
    entity: 'client',
    entity_id: CLIENT_IDS.velociti,
    description: 'Updated Velociti Fitness notes',
    timestamp: '2026-04-06T11:20:00Z',
  },
  {
    id: 'demo-act-002',
    type: 'create',
    entity: 'task',
    entity_id: 'demo-task-004',
    description: 'Created task: Set up TikTok pixel for Velociti Fitness',
    timestamp: '2026-04-03T14:00:00Z',
  },
  {
    id: 'demo-act-003',
    type: 'complete',
    entity: 'task',
    entity_id: 'demo-task-002',
    description: 'Completed: Publish April content calendar for Aurora Wellness',
    timestamp: '2026-04-02T15:30:00Z',
  },
  {
    id: 'demo-act-004',
    type: 'create',
    entity: 'invoice',
    entity_id: 'demo-inv-001',
    description: 'Created invoice GTH-042 for Pinnacle Auto Group — $4,200',
    timestamp: '2026-04-01T08:00:00Z',
  },
  {
    id: 'demo-act-005',
    type: 'payment',
    entity: 'invoice',
    entity_id: 'demo-inv-003',
    description: 'Payment received: GTH-040 from Velociti Fitness — $3,500',
    timestamp: '2026-03-12T10:30:00Z',
  },
]

export const demoData = {
  clients: demoClients,
  tasks: demoTasks,
  projects: demoProjects,
  invoices: demoInvoices,
  leads: demoLeads,
  events: demoEvents,
  campaigns: demoCampaigns,
  contacts: demoContacts,
  meetings: demoMeetings,
  services: demoServices,
  templates: [],
  goals: demoGoals,
  activity: demoActivity,
  credentials: [],
  sops: [],
  timeEntries: [],
  settings: {},
  runningTimer: null,
}
